USE CybersecurityProjects;

INSERT INTO Courses (Course_ID, Course_Name)
VALUES
(1, 'Foundations of Cybersecurity'),
(2, 'Play It Safe: Manage Security Risks');

INSERT INTO Projects
(Project_ID, Project_Name, Category, Security_Domain, Skills, Risk_Level, Google_Course, Status, Course_ID)
VALUES

('001',
 'Phishing Email',
 'Threat Analysis',
 'Security Operations',
 'Phishing Analysis',
 'Medium',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('002',
 'Keep Organizations Secure',
 'Security Fundamentals',
 'Security Operations',
 'Security Controls',
 'High',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('003',
 'Methods of Attack',
 'Threat Analysis',
 'Threat Intelligence',
 'Attack Methods, Vulnerabilities',
 'High',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('004',
 'CISSP Security Domains',
 'Security Frameworks',
 'Security Governance',
 'CISSP Domains, Security Principles',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('005',
 'Security Frameworks',
 'Security Frameworks',
 'Security Governance',
 'Frameworks, Controls',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('006',
 'Ethics in Cybersecurity',
 'Risk Management',
 'Security Governance',
 'Cyber Ethics, Professionalism',
 'Low',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('007',
 'Security Fundamentals',
 'Risk Management',
 'Security Risk Management',
 'Threat Assessment',
 'High',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('008',
 'Threats, Risks and Vulnerabilities',
 'Security Fundamentals',
 'Security Governance',
 'NIST RMF, Risk Assessment',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('009',
 'CIA Triad',
 'Security Fundamentals',
 'Security Principles',
 'Confidentiality, Integrity, Availability',
 'Medium',
 'Course 1 - Foundations of Cybersecurity',
 'Completed',
 1),

('010',
 'NIST Cybersecurity Framework',
 'Security Principles',
 'Security Governance',
 'NIST CSF, Security Frameworks',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('011',
 'OWASP Security Principles',
 'Security Audit',
 'Application Security',
 'OWASP, Secure Development',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('012',
 'Security Audit Report',
 'Security Operations',
 'Security Governance',
 'Auditing, Reporting',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('013',
 'SIEM Fundamentals',
 'Security Operations',
 'Security Monitoring',
 'SIEM, Log Analysis',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('014',
 'What are logs?',
 'Incident Response',
 'Security Monitoring',
 'Log Management',
 'Low',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('015',
 'SIEM Dashboard',
 'Security Operations',
 'Security Monitoring',
 'Dashboard Analysis',
 'Medium',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('016',
 'Incident Response',
 'Security Operations',
 'Security Operations',
 'Incident Response',
 'High',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('017',
 'SIEM Alerts Investigation',
 'Security Operations',
 'Security Monitoring',
 'Alert Investigation',
 'High',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2),

('018',
 'SIEM and SOAR',
 'Security Operations',
 'Security Monitoring',
 'SIEM, SOAR, Automation',
 'High',
 'Course 2 - Play It Safe: Manage Security Risks',
 'Completed',
 2);